app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/',auth_views.LoginView.as_view(), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    
    path('', views.home, name='home'),

    path('',include('policial.urls')),
    path('',include('categoria.urls')),
    path('',include('material.urls')),
    path('',include('cautela.urls')),
    
]

material/urls.py
from django.urls import path
from .views import MaterialListView, MaterialCreateView, MaterialDetailView, MaterialUpdateView, MaterialDeleteView


urlpatterns = [
    
    path('material/list/',MaterialListView.as_view(), name='material_list'),
    path('material/create/',MaterialCreateView.as_view(), name='material_create'),
    path('material/<int:pk>/detail/',MaterialDetailView.as_view(), name='material_detail'),
    path('material/<int:pk>/update/',MaterialUpdateView.as_view(), name='material_update'),
    path('material/<int:pk>/delete/',MaterialDeleteView.as_view(), name='material_delete'),
    
] 


    
    

categoria/models.py
from django.db import models

class Categoria(models.Model):
    categoria = models.CharField(max_length=255)
    descricao = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['categoria'] #deixa ordenado 

    def __str__(self):
        return self.categoria  

 

material/models.py
from django.db import models
from categoria.models import Categoria


class Material(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT, related_name='categorias')
    titulo = models.CharField(max_length=500)    
    patrimonio = models.IntegerField(blank=False, null=False, unique=True)
    descricao = models.TextField(null=True, blank=True)    
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['categoria','titulo']

    def __str__(self):
        return self.titulo    

material/forms.py
from django import forms
from .models import Material

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['categoria', 'titulo', 'patrimonio','descricao']
        widgets = {
            'categoria': forms.Select(attrs={'class': 'form-control'}), # formatar CSS
            'titulo': forms.TextInput(attrs={'class': 'form-control'}), # formatar CSS
            'patrimonio': forms.TextInput(attrs={'class': 'form-control'}), # formatar CSS
            'descricao': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
        labels = {
            'categoria': 'Categoria',
            'titulo': 'Título',
            'patrimonio': 'Patrimônio',
            'descricao': 'Descrição'
        }
    def clean_titulo(self):
        titulo = self.cleaned_data.get('titulo')
        # Se necessário, inclua a validação do título aqui
        return titulo
        

    def clean_patrimonio(self):
        patrimonio = self.cleaned_data.get('patrimonio')
        # Verifica se existe algum material com o mesmo patrimônio, excluindo o atual em caso de atualização
        if Material.objects.filter(patrimonio=patrimonio).exclude(id=self.instance.id).exists():
            raise forms.ValidationError("Já existe um material com esse patrimônio.")
        return patrimonio

material/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models, forms

class MaterialListView(LoginRequiredMixin, ListView):
    model = models.Material
    template_name= 'material_list.html'
    context_object_name = 'materiais'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        titulo = self.request.GET.get('titulo')

        if titulo:
            queryset = queryset.filter(titulo__icontains=titulo)

        return queryset

class MaterialCreateView(LoginRequiredMixin, CreateView):
    model = models.Material
    template_name = 'material_create.html'
    form_class = forms.MaterialForm
    success_url = reverse_lazy('material_list')

class MaterialDetailView(LoginRequiredMixin, DetailView):
    model = models.Material
    template_name = 'material_detail.html'  

class MaterialUpdateView(LoginRequiredMixin, UpdateView):    
    model = models.Material
    template_name = 'material_update.html'
    form_class = forms.MaterialForm
    success_url = reverse_lazy('material_list')         

class MaterialDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Material
    template_name = 'material_delete.html'
    success_url = reverse_lazy('material_list')

material/templates/material_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-sm mt-4" >
        <h3 class="display-6">Cadastro de Material</h3>

        <div class="card">
            <div class="card-body">
                <form class="form" method="post">
                    {% csrf_token %}
                    
                    {{form.as_p}}
                    
                    <button type="submit" class="btn btn-primary">Salvar Material</button>
                </form>
                
            </div>
        </div>
        <a href="{% url 'material_list' %}" class="btn btn-secondary mt-3">Cancelar e voltra Lista de Material</a>
    </div>
{% endblock %}

material/templates/material_delete.html
{% extends 'base.html'%}

{% block  content %}
    <div class="container mt-4">
        <h3 class="display-6">Deletar Material</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza de que deseja excluir o material com Patrimônio: <strong>{{ object.patrimonio}}</strong> ?</p>
                <form class="form" method="post">
                    {% csrf_token %}
                    {{ form.as_p}}
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </div>
        </div>
        <a href="{% url 'categoria_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para Lista de Materiais</a>
    </div>
{% endblock %}

material/templates/material_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Detalhes do Material</h3>

    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{object.titulo}} </h3>
            <p class="card-text"> Categoria: {{object.categoria}}</p>
            <p class="card-text"> Patrimônio: {{object.patrimonio}}</p>
            <p class="card-text"> Descrição: {{object.descricao}}</p>
            
        </div>
    </div>
    <a href="{% url 'material_list' %}" class="btn btn-secondary mt-3">Voltar para Lista de Materiais</a>
</div>

{% endblock %}

material/templates/material_list.html
{% extends 'base.html' %}

{% block title %}
Cautela - Material
{% endblock %}

{% block content %}
<h2>Material</h2>
    <div class="row mb-3">
        <div class="col-md-6">
            <form  method="get" action="{% url 'material_list'%}">
                <div class="input-group">
                    <input type="text" class="form-control" name="titulo" placeholder="Titulo" value="{{ request.GET.titulo}}">
                    <button type="submit" class="btn  btn-primary">
                        <i class="bi bi-search"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <a href="{% url 'material_create' %}" class="btn btn-success float-end">
                <i class="bi bi-plus">Novo Material</i>
            </a>
        </div>
        
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>                    
                    
                    <th>ID </th>
                    <th>Categoria </th>
                    <th>Título</th>                    
                    <th>Patrimônio</th>                    
                    <th>Descrição</th>                    
                </tr>
            </thead>
            <tbody>
                {% for material in materiais %}
                <tr>
                    <td>{{material.id}}</td>
                    <td>{{material.categoria}}</td>
                    <td>{{material.titulo}}</td>                    
                    <td>{{material.patrimonio}}</td>                    
                    <td>{{material.descricao}}</td>                    
                    <td> 
                        <a href="{% url 'material_detail' material.id %}" class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i>
                        </a>
                        <a href="{% url 'material_update' material.id %}"  class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="{% url 'material_delete' material.id %}" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% include 'components/_pagination.html' %}
{% endblock %}

material/templates/material_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-sm mt-4" >
        <h3 class="display-6">Atualizar  Material</h3>

        <div class="card">
            <div class="card-body">
                <form class="form" method="post">
                    {% csrf_token %}
                    
                    {{form.as_p }}
                    
                    <button type="submit" class="btn btn-primary">Salvar Atualização</button>
                </form>
                {% if form.non_field_errors %}
                    <div class="errors">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                {% endfor %}
                    </div>
    {% endif %}
                
            </div>
        </div>
        <a href="{% url 'material_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
    </div>
{% endblock %}